name: Get Key

on:
  workflow_dispatch:

jobs:
  update:
    name: Update keys
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: key

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run deobfuscation
        run: node deobfuscate.js

      - name: Extract arrays and generate key
        run: node extractor.js

      - name: Checkout ${{ matrix.branch }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          path: key_repo

      - name: Update extracted arrays if they differ
        run: |
          cd key_repo
          ls ./
          if [[ -f "../extracted_arrays.json" ]]; then
            if [[ ! -f "extracted_arrays.json" ]] || [[ "$(cat extracted_arrays.json 2>/dev/null || echo '')" != "$(cat ../extracted_arrays.json)" ]]; then
              cp ../extracted_arrays.json .
              git config --local user.email "github-actions[bot]@users.noreply.github.com"
              git config --local user.name "github-actions[bot]"
              git add extracted_arrays.json
              git commit --amend -m "chore: Update extracted arrays and decryption key"
              git push --force
            else
              echo "extracted_arrays.json not change"
            fi
          else
            echo "Not found file extracted_arrays.json"
          fi

  # Workaround for CI schedule event, to prevent it's delays (5min ~ 1h!)
  manual-rerun:
    name: Re-run workflow
    permissions:
      actions: write
    needs: update
    # Always run, except when manually cancelled.
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 minutes
        run: sleep 300

      - name: Re-trigger workflow
        run: gh workflow run get-key.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}